#!/bin/bash

_PWD=$PWD
_TYPE=$1
_NOW=$(date +"%y%m%d_%H%M%S")
_NOTE="${_TYPE}_${_NOW}.note"
_HOME="$HOME/notebook"
_BOOK="$_HOME/$_TYPE"

if [ $# -eq 0 ]; then
	echo "$(ls $_HOME)"
else
	if [ ! -d "$_HOME" ]; then
		mkdir $_HOME
	fi

	if [ ! -d "$_BOOK" ]; then
		mkdir "$_BOOK"
	fi
	vim "$_BOOK/$_NOTE"
fi
